# Generated by Django 2.2.3 on 2019-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinylinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinylink',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='tinylink',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last validation'),
        ),
        migrations.AlterField(
            model_name='tinylink',
            name='redirect_location',
            field=models.CharField(default='', max_length=2500, verbose_name='Redirect location'),
        ),
        migrations.AlterField(
            model_name='tinylink',
            name='validation_error',
            field=models.CharField(default='', max_length=100, verbose_name='Validation Error'),
        ),
        migrations.AddIndex(
            model_name='tinylink',
            index=models.Index(fields=['short_url'], name='tinylinks_t_short_u_ee1953_idx'),
        ),
    ]
